### ISSUE TITLE
路由权限控制

### ISSUE THREAD

**Issue by jisuz** [yimogit/me-admin-template#2]
你好，我最近在做vue的路由权限控制，参考了你的文章和代码，有写地方看不懂，想请教一下哈。

1.想问一下代码中好像没有体现到路由权限控制这一部分，想问一下这个怎么实现
路由中定义是否需要验证权限：meta:{ auth :true }
就是这个地方，想问一下怎么判断当前角色是否有权限可以访问这个界面

**Comment by yimogit** [comment]
简而言之就是根据接口返回的modules，判断当前路由的name是否存在modules，不存在则就跳转登录页等操作

### 1. 登录成功之后返回用户所有的模块编码 [code]( https://github.com/yimogit/me-admin-template/blob/master/mock-server/api/v1/account/getinfo.js#L100)  
![image](https://user-images.githubusercontent.com/15975059/47422085-757cd300-d7b4-11e8-9c75-e454702310fd.png)



### 2. 路由守卫中进行判断[code](https://github.com/yimogit/me-admin-template/blob/master/src/router/logic.js)
路由钩子这里判断一下即可
![image](https://user-images.githubusercontent.com/15975059/47422628-a8739680-d7b5-11e8-81ee-096279f8493a.png)

**Comment by jisuz** [comment]
好的，万分感谢哈，我回去试试看哈，谢谢

**Comment by yimogit** [comment]
翻车了，刚刚判断写错了，参考思路即可~
