### ISSUE TITLE
请问一下node版本是多少，安装以来失败 使用 16.13.1 版本的

### ISSUE THREAD

**Issue by zuoerji** [yimogit/me-admin-template#4]
请问一下node版本是多少，安装以来失败 使用 16.13.1 版本的
<img width="649" alt="image" src="https://user-images.githubusercontent.com/24914290/168793233-0bdef175-04f3-415a-b0a4-aba932756c1c.png">

**Comment by yimogit** [comment]
8 试试 
![image](https://user-images.githubusercontent.com/15975059/169632440-bcaf45b3-1e95-420e-9ee1-ccdd77ff5306.png)
